version: '3'

services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=asdasd
